services:
  ci:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - YAKAPI_URL=http://172.17.0.1
    command: python -u ci.py
    volumes:
      - .:/app
      - ../yakapi/yakapi_package:/yakapi_package

  roversim:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - YAKAPI_URL=http://172.17.0.1
      - REDIS_URL=redis://172.17.0.1:6379/0
    command: python -u main.py
    volumes:
      - .:/app
      - ../yakapi/yakapi_package:/yakapi_package
